### ISSUE TITLE
Bir Sorun

### ISSUE THREAD

**Issue by haksaya** [ugurarici/lyk2015_php-oop#1]
Parse error: syntax error, unexpected '[' in /home/domain.com/httpdocs/restaurant/model/Order.php on line 58

Böyle bir hata alıyorum.

**Comment by ugurarici** [comment]
Bu sorun bu proje için değil ugurarici/restaurant için sanıyorum. Öyleyse o satırda bir dizi açmak için `$items = [];` demişiz, `[]` şeklindeki kısa yazımı desteklemiyor olabilir PHP yorumlayıcınız, sürümünüzü ve bu ayarı bir kontrol edin derim.

Eğer sorun bundan kaynaklanıyorsa, o satırı `$items = [];` yerine `$items = array();` şeklinde düzenleyerek bu durumu giderebilirsiniz.
